# Generated by Django 4.0.10 on 2023-06-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='lint',
            new_name='link',
        ),
    ]
